config/routes.rb
Rails.application.routes.draw do
  resources :short_links
  root 'short_links#index'
  get 'short_links/fetch/:slug', to: 'short_links#fetch'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/short_link.rb
class ShortLink < ApplicationRecord
  #URL_REGEX = /\A(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w\.-]*)*\/?\Z/i
  URL_REGEX = /\A(http:\/\/|https:\/\/)?[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?\Z/i

  after_create :generate_short_url
  before_create :sanitize

  validates_format_of :main_url, :with => URL_REGEX
  validates :main_url, :presence=>true, :uniqueness=>true

  def generate_short_url
    # generates short_url/slug for object using object id
    # expire_date of a object is created /renewed when user requests to create
    # new/existing short url
    # TODO: all short_links can be cleaned up based on expire date, so that
    # we can archive older short url request
    self.slug = id.to_s(36)
    self.expire_date = Date.today + 30.days
    self.save
  end

  def new_url?
    find_existing.nil?
  end

  def find_existing
    self.sanitize
    ShortLink.find_by(sanitize_url: self.sanitize_url)
  end

  def sanitize
    # sanitize user input url to avoid duplicate data in system
    if main_url.present?
      main_url.strip!
      url = self.main_url.downcase.gsub(/(https?\:\/\/)|www\./,'')
      self.sanitize_url = "http://" + url
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery unless: -> { request.format.json? }

end

app/controllers/short_links_controller.rb
class ShortLinksController < ApplicationController
  before_action :set_short_link, only: [ :update]
  respond_to :html,:json,:js
  after_action :increase_hit_count, only: [:fetch]

  def index
    @short_links = ShortLink.all.order("hit_count desc").limit(100)
    @short_link = ShortLink.new
  end

  def show
    slug = params[:id]
    @short_link = ShortLink.find_by_slug(slug)
    @short_link.hit_count+=1
    @short_link.expire_date = Date.today + 30.days
    @short_link.save
    redirect_to '/short_links/'+@short_link.main_url
    return
  end

  def fetch
    # finds main url based on slug
    # increases hit count by 1
    slug = params[:slug]
    @short_link = ShortLink.find_by_slug(slug)
    # @short_link.hit_count += 1
    # @short_link.save
    redirect_to @short_link.main_url
    return
  end

  def new
    @short_link = ShortLink.new
  end


  def create
    short_link = ShortLink.new(short_link_params)
    if short_link.new_url?
      short_link.save
      @short_link = short_link
    else
      @short_link = short_link.find_existing
      @short_link.expire_date = Date.today + 30.days
      @short_link.save
    end
    respond_with @short_link
  end


  def update

  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_short_link
    @short_link = ShortLink.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def short_link_params
    params.require(:short_link).permit(:main_url)
  end


  def increase_hit_count
    if @short_link.present?
      @short_link.hit_count += 1
      @short_link.save
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="panel panel-default footer">
    
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="header">
  <div class="jumbotron header">
  <h1>ShortenUrl<h1>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShortenUrl</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': true %>
  </head>

  <body>

      <%= render "layouts/header" %>
      <div class="container">


        <%= yield %>
      </div>
    <%= render "layouts/footer" %>

  </body>
</html>

app/views/short_links/_form.html.erb
<%= form_for(@short_link, :format => :js,remote: true) do |form| %>
  <% if @short_link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@short_link.errors.count, "error") %> prohibited this short_link from being saved:</h2>

      <ul>
      <% @short_link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <!--%= link_to image_tag("logo.png"), root_path %-->
  </div>
  <div class="field">
    <%= form.text_field :main_url, :class => "form-control", :placeholder => "Paste a link to shorten" %>
  </div>
  <div class="actions create_link">
    <%= form.submit 'Click Me', :class => "btn btn-primary"%>
  </div>
<% end %>

app/views/short_links/_new_link.html.erb
<h5>Generate Short Link with us </h5>
<div id="result">
</div>

<%= render 'form', short_link: @short_link %>

app/views/short_links/create.js.erb
<% if @short_link.errors.messages.present? == false%>
$('#result').html('<p class="short_url">Your Link <%= @short_link.main_url%>: <%= link_to "#{ENV['HOST_URL']}/short_links/fetch/#{@short_link.slug}", controller:'short_links', action:'fetch', slug:@short_link.slug %></p>')
<% else %>
$('#result').html('<p class="short_url" style="color:red">Some error occured, Please verify URL again.  </p>')
<% end %>

app/views/short_links/edit.html.erb
<h1>Editing Short Link</h1>

<%= render 'form', short_link: @short_link %>

<%= link_to 'Show', @short_link %> |
<%= link_to 'Back', short_links_path %>

app/views/short_links/index.html.erb
<div class="container">

  <div style='float:right'>
  <%= link_to 'Reload', root_path, :class => "btn btn-primary " %>
  </div>
  <br>

  <div>
  <%= render 'new_link', remote: true%>



</div>
<br>


    <table class="table table-bordered table-striped">
    <thead class="thead-dark">
      <tr>
        <th>Main url</th>
        <th>Slug</th>
        <th>Hit count</th>
        <th>Expire date</th>
      </tr>
    </thead>

    <tbody>
      <% @short_links.each do |short_link| %>
        <tr>
          <td><%= short_link.main_url %></td>
          <td><%= link_to("#{ENV['HOST_URL']}/short_links/fetch/#{short_link.slug}",
            controller:'short_links', action:'fetch', slug:short_link.slug)
            %>
          </td>
          <td><%= short_link.hit_count %></td>
          <td><%= short_link.expire_date.to_s %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>